app:
  name: "wzj-sign"
  version: "1.0.1"
  port: 10086
  model: "dev"
position:
  lat: "30.520517"
  lon: "114.423792"

email:
  host : "smtp.qq.com"
  port : 465
  userName : "joker.xueo717@foxmail.com"
  password : "ayrmnuxysgvmjcjj"
map:
  key: "W4HBZ-GARKZ-MR6XX-7VK4M-VECNF-A5FQG"  # 请替换为你自己的腾讯地图Key（已加入配置）


